#!/bin/sh
set -e

# Ensure /code/web directory exists, preventing Apache from crashing.
mkdir -p /var/www/html

# If it's set, ensure $WEB_PATH starts with a slash.
WEB_PATH=$(echo ${WEB_PATH} | sed 's#^\([^/]\)#/\1#')

# Unset $WEB_PATH if it's just a slash. Otherwise Apache does weird things.
if [ "$WEB_PATH" == "/" ]; then
  unset WEB_PATH
fi

# If $PUBLIC_DIR is set, symlink it to /shared/public and correct permissions.
if [ "${PUBLIC_DIR}" ]; then
  mkdir -p /shared/public
  # Only create symlink if it does not already exist.
  if [ ! -h /var/www/${PUBLIC_DIR} ]; then
    ln -sf /shared/public /var/www/${PUBLIC_DIR}
  fi
  chown -R www-data:www-data /shared/public
fi

# If $PRIVATE_DIR is set, ensure it exists and has correct permissions.
if [ "${PRIVATE_DIR}" ]; then
  mkdir -p ${PRIVATE_DIR}
  chown -R www-data:www-data ${PRIVATE_DIR}
fi

exec apache2 -D FOREGROUND
